### PR TITLE
Add German Translation

### PR DESCRIPTION
**Pull request by fredericmarx**
Hey folks,

I translated the intro text to German and added some German resources.
This isn't an exhaustive list by any means; I just wanted to provide a baseline so German resources can be easily added.

- There is no language navigation (yet); the German version would be available via `shitty.men/de`.
- I didn't find any (constructive) German resources on microaggressions; feel free to add them if you know some.
- I also didn't find any "5 accidentally transphobic phrases allies use"-type listicles in German. More of those would be great if you know any.
- I added some links about gendered language *(Geschlechtergerechte Sprache)* as it's an important Germanism that should be adressed imo.

Thanks for your work, this is an awesome project!

### CODE REVIEW

**Comment by Charlotteis** [comment]
Could you add the language attribute to your HTML tag? This'll tell screenreaders the correct accent to use. https://www.w3.org/International/questions/qa-lang-why.en#access

so yours might be
`<html lang="de">` :)

**Comment by fredericmarx** [comment]
Thanks, @Charlotteis :)

**Comment by lewiscowper** [comment]
So I have a few thoughts.

- I need to get the sources/resources approved and stuff from a third party who speaks German and knows more of this stuff that I do. I can take care of that.
- I've now added the `lang="en"` attribute to the english page, so removing that commit from this PR would be :100: :+1:
- We should add some understated links to translated versions under the top border, but before the main content, once this is merged, I'll put up my current idea for suggestions.

**Comment by lewiscowper** [comment]
Closing this in favour of merging #4 once reviewed. :)

Once #4 goes in, we can add links in a separate PR so as not to clutter it :+1:

**Pull request closed without merging**
